### PR TITLE
more meg examples

### PR DESCRIPTION
**Pull request by guiomar**
Replaces #50

### CODE REVIEW

**Comment by jasmainak** [comment]
I see some files which are `_fid.json`. Weren't they supposed to have gone?

**Comment by guiomar-niso** [comment]
There shouldn't be. I'll double check.

**Comment by guiomar** [comment]
There shouldn't be. I'll double check.

**Comment by guiomar** [comment]
I can't see them. Could you point the path? Thanks!

**Comment by guiomar** [comment]
Nice :)

**Pull request merged**
