### PR TITLE
Merge remote-tracking branch 'guiomar/bep008_meg' into bep008_meg

### PR DESCRIPTION
**Pull request by guiomar**

### CODE REVIEW

**Comment by jasmainak** [comment]
@guiomar you have some problem with your commits ...

maybe you can cherry-pick your last 3 commits. If you don't manage by tomorrow, I'll try to help :)

**Comment by guiomar** [comment]
Hi @jasmainak !

These are the things I see in the validator for ds00246 and ds00247:

1) CoilsCoordinates, etc have been renamed by HeadCoildCoordinates, etc.
Check out the merged specs in the general bids document. 
(I think this is not updated into the validator yet)

2) Also especial attention should be given to the emptyroom subject. It won't have the same number of files as the other subjects.

3) The field IntededFor also seems to complain, maybe because of the format?

**Comment by jasmainak** [comment]
okay, I made some updates to the validator for 1. I notice these issues:

```sh
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'FiducialsDescription'
		./sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_proc-tsss_meg.json
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'TaskName'
		./sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_proc-tsss_meg.json
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'SamplingFrequency'
		./sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_proc-tsss_meg.json
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'DewarPosition'
		./sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_proc-tsss_meg.json
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'DigitizedLandmarks'
		./sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_proc-tsss_meg.json
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'DigitizedHeadPoints'
		./sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_proc-tsss_meg.json
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'Manufacturer'
		./sub-13/ses-meg/sub-13_ses-meg_task-facerecognition_proc-tsss_meg.json
			JSON file is not formatted according the schema.
			Evidence:  should have required property 'PowerLineFrequency'
```

where do you see 3.? can you point me to the file?

**Comment by guiomar** [comment]
Thanks!!

**Comment by guiomar** [comment]
Hi @jasmainak !

New things:

1) Should CoilFrequency should be changed to HeadCoildFrequency to match the other fields? --> In this field, there could be times when there's not just a number but a vector of numbers, e.g. coils working at 3 different frequencies (which is the case in our ctf system).

2) When it says a file: should NOT have additional properties
Could we get the corresponding fields it is referring to?

Regarding point 3 before, you can check the warnings in ds00246:

`view 1 warning in 47 files
Warning: 1
Not all subjects contain the same files. Each subject should contain the same number of files with the same naming unless some files are known to be missing.47 files
sub-0001_task-noise_run-01_channels.tsvNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_channels.tsv

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

BadChannelsNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/BadChannels

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

ClassFile.clsNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/ClassFile.cls

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

default.deNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/default.de

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

params.dscNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/params.dsc

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

processing.cfgNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/processing.cfg

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

sub-emptyroom_task-noise_run-01_meg.acqNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/sub-emptyroom_task-noise_run-01_meg.acq

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

sub-emptyroom_task-noise_run-01_meg.hcNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/sub-emptyroom_task-noise_run-01_meg.hc

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

sub-emptyroom_task-noise_run-01_meg.histNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/sub-emptyroom_task-noise_run-01_meg.hist

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

sub-emptyroom_task-noise_run-01_meg.infodsNaN KB |
Location:
/sub-0001/meg/sub-0001_task-noise_run-01_meg.ds/sub-emptyroom_task-noise_run-01_meg.infods

Reason:
This file is missing for subject sub-0001, but is present for most other subjects.

View 37 more files`

**Comment by jasmainak** [comment]
> Should CoilFrequency should be changed to HeadCoildFrequency to match the other fields?

okay, I saw your comment on the BIDS draft to update this. I updated the validator for this, but I would say that the validator for now should be made to work on version 1.0, otherwise we will never converge :-)

>  --> In this field, there could be times when there's not just a number but a vector of numbers, e.g. coils working at 3 different frequencies (which is the case in our ctf system).

okay fixed!

> When it says a file: should NOT have additional properties
Could we get the corresponding fields it is referring to?

umm ... I don't think so. The problem is that the validator uses a javascript library called `ajv` which recommends against doing so. See the FAQ here: https://epoberezkin.github.io/ajv/faq.html. I am not sure I understand fully though :)

**Comment by guiomar** [comment]
Ok, thanks!! Yes, no more changes to the specs :)

**Comment by guiomar** [comment]
Ok, I understand the javascript library, but then it's difficult to track. I'll try to add fields progressively until I find the not included ones...

**Comment by guiomar** [comment]
@jasmainak any clue of the "should NOT have additional properties" errors we are getting with these ds00246 and ds00247 datasets? I think we are really following the specs. Can you see anything?

**Comment by jasmainak** [comment]
okay let me look into it :-)

**Comment by jasmainak** [comment]
okay ds00246 was my fault :) we were missing a field `ManufacturersModelName` in the schema. As for ds00247, I noticed that there is still a field called `CoilFrequency`. It should be `HeadCoilFrequency` now. Any other dataset I can look into?

**Comment by guiomar** [comment]
Thanks! updated :)

**Comment by jasmainak** [comment]
ready to merge? It passes the validator for me

**Comment by guiomar** [comment]
Yes, for me too!

Only the warnings for empyi nii etc, but no errors :)

**Comment by jasmainak** [comment]
let's merge then :) :beers:

**Comment by guiomar** [comment]
Yes!! Go ahead! Thanks!! :D

**Pull request merged**
