### PR TITLE
ds000117 EEGonly added

### PR DESCRIPTION
**Pull request by CPernet**
This is the full data set for EEG only using the latest BIDS spec

### CODE REVIEW

**Comment by chrisfilo** [comment]
It seem this PR is mixing commits from multiple sources. 

Additionally `ds000117-EEGonly` datasets seems to use `subXXX` instead of `sub-XXX`. Stimuli files should go into `/stimuli` (lower caps).

**Comment by chrisfilo** [comment]
I'm still seeing a lot of changes that seems unrelated (for example deletion of a lot of files from `7t_trt`). Not sure what happened here. Maybe it would be best to move the changes manually and start over from `bep006_eeg`.

**Comment by robertoostenveld** [comment]
this could be closed if #75 gets merged

**Comment by robertoostenveld** [comment]
The eek-only version has been merged

**Pull request closed without merging**
