### PR TITLE
Multispectral examples

### PR DESCRIPTION
**Pull request by suyashdb**

### CODE REVIEW

**Comment by emdupre** [comment]
Since multi-echo BOLD has been merged into the BIDS spec, can these changes be merged as an example dataset? Would be helpful to have for testing.

**Comment by chrisfilo** [comment]
In principle yes, but this PR is outdated (using _meepi suffixes we ended up not using) and includes structural multi echo which was not released. @suyashdb could you open a new PR with only bold multi echo?

@emdupre multi echo bold dataset have been revised on OpenfMRI and should be up to date with the spec. It's only this repo that is lagging behind.

**Comment by suyashdb** [comment]
@chrisfilo Sure.

**Comment by chrisfilo** [comment]
@suyashdb could you open a new PR with only bold multi echo?

**Comment by emdupre** [comment]
We were discussing the possibility of adding multi-echo examples in https://github.com/poldracklab/fmriprep/issues/914. Should I make a new PR, here, or is this still WIP? Please let me know what would be best!

**Comment by suyashdb** [comment]
@emdupre  i just have to create a new PR for multiecho bold data as per chris previous comment. Once merged that should suffice for adding example to fmriprep?

**Comment by emdupre** [comment]
Yes, that would be great! I just wasn't sure what your time frame was for creating that PR. Let me know what I can do to help.

**Comment by suyashdb** [comment]
PR #43

**Pull request closed without merging**
