### PR TITLE
Bep006 eeg

### PR DESCRIPTION
**Pull request by CPernet**
this fork contains EEG data only (not sure if easier to merge) all updated for the last specification

### CODE REVIEW

**Comment by CPernet** [comment]
added a new dataset + MR datasets from master (of today, forgot to push them)

**Comment by robertoostenveld** [comment]
there are still 665 changed files. It seems that many of them are changes in file permissions. I will try to cherry pick...

**Comment by robertoostenveld** [comment]
The commits are not clean, I will make a new PR and include the changed files for each dataset separately.

**Comment by robertoostenveld** [comment]
this has been superseded by PR #88 #89 #90 and #91

**Comment by robertoostenveld** [comment]
for reference, this is what I did after checking out this PR

```
zip -r ds_cbm.zip ds_cbm
zip -r eeg_rishikesh.zip eeg_rishikesh
zip -r eeg_sleep.zip eeg_sleep
zip -r ds000117_eeg_only.zip ds000117_eeg_only
```

after this, I checked out bep006_eeg, made a branch for each of the parts, removed the old files  (e.g.  rm -rf ds_cbm) then added the ones from the zip (unzip ds_cbm.zip) then committed the changes, then pushed the changes on each branch.

**Pull request closed without merging**
