### PR TITLE
Updating MEG-BIDS datasets:

### PR DESCRIPTION
**Pull request by guiomar**
ds246: MEG-BIDS Brainstorm data sample 
ds247: MEG-BIDS OMEGA sample 

(thanks Beth Bock)

### CODE REVIEW

**Comment by jasmainak** [comment]
Thanks Guio! I think `.nii.gz` files are not normally in this repo (if I'm not mistaken) because they bloat the git repo ...

**Comment by guiomar** [comment]
Ok! Then I'll replace them with empty files (the same we did for the meg4) or should I directly remove them?

**Comment by jasmainak** [comment]
hmm ... I'm not sure.

**Comment by guiomar** [comment]
Done! I've just emptied them :)

**Comment by jasmainak** [comment]
you need to squash, otherwise it remain in git history :-) git works in mysterious ways ;-)

**Pull request closed without merging**
