### PR TITLE
[MRG] validate against main repo using --bep006 flag

### PR DESCRIPTION
**Pull request by sappelhoff**
the eeg-validator has been merged, use main repo from now on.

We have to use the `--bep006` flag until the EEG spec is fully merged with the main spec.

### CODE REVIEW

**Comment by jasmainak** [comment]
Travis is failing

**Comment by sappelhoff** [comment]
part of the fixes will persist until #110 is merged

**Comment by sappelhoff** [comment]
actually, Travis is only failing because of the EEG examples. So this PR will be clean once #110 is merged.

**Comment by jasmainak** [comment]
okay, sounds good

**Pull request closed without merging**
