### PR TITLE
corrections to json files: added required fields

### PR DESCRIPTION
**Pull request by dorahermes**
the correction to the json files include adding required fields, fixing characters that were not allowed, but some of the field values are still empty

### CODE REVIEW

**Comment by robertoostenveld** [comment]
@ftadel do you agree?

**Comment by ftadel** [comment]
I'm sorry, I haven't been following this much recently...
@ebock, @guiomar-niso, @jeremymoreau, @martcous: has anybody been keeping track of these files?

**Comment by jasmainak** [comment]
These files are necessary for writing the MEG BIDS validator: https://github.com/INCF/bids-validator/pull/301. The tests depend on this being in the correct format ... I guess the bep008_meg branch will be eventually merged into the master, is that correct @chrisfilo ?

**Comment by chrisfilo** [comment]
Yes this is correct. I would recommend making this PR a woork-in-progress and temporarily using the bep008_meg branch of the bids-examples until we merge everything in.

**Comment by ebock** [comment]
The updated versions of our examples are on the OMEGA dropbox: https://box.bic.mni.mcgill.ca/apps/files/?dir=/OMEGA%20(2)/Contributions%20(in%20BIDS%20format)&fileid=49426. Please use them to help write the validator and let me know if there are any errors (or let me know if I can help).

**Comment by dorahermes** [comment]
I do not have access to the box link in the OMEGA dropbox, does this have updated json files? Can anyone push them to the bep008_meg branch? wrt this PR: @chrisfilo this PR is just to update the json files in the bep008_meg branch (all required fields are there according to the google docs, but the fields have not been filled yet).

**Comment by chrisfilo** [comment]
Ah yes - sorry I confused it with the PR to the validator.

**Comment by guiomar** [comment]
Hi! I think this is already fixed. Do you think there is something else remaining here?

**Pull request closed without merging**
