### PR TITLE
Update ReferencesAndLinks for array of strings requirement.

### PR DESCRIPTION
**Pull request by nellh**
This updates all dataset_description.json files to consistently use an array of strings for ReferencesAndLinks.

### CODE REVIEW

**Comment by jasmainak** [comment]
shouldn't this be tested in the validator?

**Comment by nellh** [comment]
Yes, this PR updates these examples so the validator tests will pass for these datasets after adding this to validation.

One other thing to note, I did split some `\n\n` delimited references up into separate array elements in three datasets: ds102, ds105, and ds113b. I left in single newlines.

**Comment by jasmainak** [comment]
yep that looks good and I saw your PR on the validator repo too :-)

**Comment by chrisfilo** [comment]
Perfect! Thanks! I'll merge and create a new release.

**Pull request merged**
