### PR TITLE
Merge master into bep006

### PR DESCRIPTION
**Pull request by robertoostenveld**
the master branch has moved on quite a bit. The consequence is that bep006_eeg is getting outdated and more difficult to maintain/update. This PR aims to synchronize the two again. 

There are no changes other than the ones that have been merged into master.

### CODE REVIEW

**Comment by robertoostenveld** [comment]
I think that quite some of the changes in @CPernet pull request #66 actually relate to this.

**Comment by robertoostenveld** [comment]
Hmm, I don't know how to deal with the failing test. I totally agree that some datasets in the bep006_eeg branch are not yet BIDS compliant, but I do think that merging this PR would be the best to move forward. This PR is not meant to deal with the EMBLA and rikesh datasets

**Comment by robertoostenveld** [comment]
Hi @chrisfilo, are you OK with me merging this?

**Comment by chrisfilo** [comment]
Yes please go ahead (sorry swamped at work).

**Pull request merged**
