### PR TITLE
include BrainStorm sample auditory dataset in BIDS-MEG format

### PR DESCRIPTION
**Pull request by robertoostenveld**
the data files have all been truncated (i.e. set to 0 bytes)

### CODE REVIEW

**Comment by robertoostenveld** [comment]
@ftadel I would like to include the (nullified) BrainSorm auditory BIDS example dataset to the INCF. It will first go into the bep008_meg branch. Once the MEG proposal is finalized, it will be merged in master. Agreed?  I could not find the github account of Sylvain and Beth, perhaps you could involve them here in this PR.

Having it in the INCF repository allows to get people to comment on the metadata (json/tsv files) and provide suggestions  for improvements.

**Comment by ftadel** [comment]
Sure! We have three example datasets available here: 
https://github.com/brainstorm-tools/bst-data-examples

They haven't been updated recently, so they might not contain the last updates of the BIDS-MEG specs.
@guiomar-niso @agramfort @martcous @ebock @sbaillet Could you check this?

**Comment by robertoostenveld** [comment]
See also #23 and #24

**Comment by ebock** [comment]
No, they are not up to date. They were converted a while back but some
changes have been made to the spec more recently and I have not updated
them. I can do this next week.

Beth

**Comment by robertoostenveld** [comment]
Let me merge my own commit into bep008_meg, then you can send me pull requests to update it. Comparing the different example datasets in bep008 should help in identifying the inconsistencies.

Robert

**Pull request merged**
